server:
  port: 50000

spring:
  datasource:
    url: jdbc:h2:mem:demo
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

backbase:
  my_secret: ${MY_SECRET:my yaml secret}

holiday:
  api:
    key: f8841219-9126-4d8a-8030-adf28f6da8d0
